name: Check Open WebUI Helm Charts (pipelines)

on:
  pull_request:
  push:
    paths:
      - "charts/pipelines/**"

jobs:
  lint-chart:
    name: Lint Helm Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
      
      - name: Lint pipelines Helm Chart
        run: |
          helm lint ./charts/pipelines

  test-deploy:
    name: Test Chart Deployment
    runs-on: ubuntu-latest
    needs: lint-chart

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v4

      - name: Set up KinD Cluster
        uses: kind-ci/actions/kind@v1
        with:
          config: |
            kind: Cluster
            apiVersion: kind.x-k8s.io/v1alpha4
            nodes:
              - role: control-plane

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Template open-webui Helm Chart
        run: |
          helm template pipelines ./charts/pipelines \
            --namespace test-namespace --create-namespace > pipelines.yaml

      - name: Verify pipelines
        run: |
          kubectl apply -f pipelines.yaml

