name: Check Open WebUI Helm Charts (open-webui)

on:
  pull_request:
  push:
    paths:
      - "charts/open-webui/**"

jobs:
  lint-chart:
    name: Lint Helm Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Lint open-webui Helm Chart
        run: |
          helm lint ./charts/open-webui

  test-deploy:
    name: Test Chart Deployment
    runs-on: ubuntu-latest
    needs: lint-chart

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v4

      - name: Set up KinD Cluster
        uses: kind-ci/actions/kind@v1
        with:
          config: |
            kind: Cluster
            apiVersion: kind.x-k8s.io/v1alpha4
            nodes:
              - role: control-plane

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Template open-webui Helm Chart
        run: |
          helm template open-webui ./charts/open-webui \
            --namespace test-namespace --create-namespace > open-webui.yaml

      - name: Verify open-webui
        run: |
          kubectl apply -f open-webui.yaml